#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'commit linting...'
echo -en "How r you [ 'Shawn' ] "
exec < /dev/tty read name
if [ -z "$name" ]; then
name=`whoami`
fi
echo "Name is : $name"

npx --no -- commitlint --edit $1

if [ $? -ne 0 ];
then
	echo 'inside'
 	$(exec < /dev/tty && node_modules/.bin/cz --hook) || true
 fi;
echo $success
