#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

echo 'commit linting...'

if  npx --no -- commitlint --edit $1
then
    echo 'inside'
else
    echo 'error'
    exec < /dev/tty && node_modules/.bin/cz --hook || true
fi

echo $success
