name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List the dir & files
        run: |
          pwd
          ls
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: List the dir & files
        run: |
          pwd
          ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Shawn
      - name: Log greeting time
        run: echo "${{steps.greet.outputs.time}}"

