name: CI
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencues
        run: npm ci
      
      - name : build
        run: npm run build
      - name : List the dir & files
        run: |
          pwd
          ls -a
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build
        run: npm run test
